FormOnline/Controllers/DataController.cs
using FormOnline.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormOnline.Controllers
{
    public class DataController : Controller
    {

        DataDbContext context = new DataDbContext();

        //
        // GET: /Data/

        public ActionResult Index()
        {
            List<Form> forms = context.Forms.ToList();

            //Tri par ordre alphabétique
            forms = forms.OrderBy(i => i.Title).ToList();

            //On vérifie si la liste de formulaires n'est pas vide
            if (forms != null)
            {
                if (forms.Count > 0)
                {
                    //On lance la fonction pour vérifier les dates de clôtures
                    forms = CheckDate(forms);
                }
            }

            return View(forms);
        }

        /// <summary>
        /// Fonction qui vérifie les dates de cloture
        /// </summary>
        /// <param name="forms"></param>
        /// <returns></returns>
        public List<Form> CheckDate(List<Form> forms)
        {
            if (forms != null)
            {
                if (forms.Count > 0)
                {
                    //Pour chaque formulaire
                    foreach (Form form in forms)
                    {
                        DateTime dateForm = form.ClosingDate;
                        DateTime dateNow = DateTime.Today;

                        int resul = DateTime.Compare(dateNow, dateForm);

                        //La date du formulaire est inférieure à la date d'aujourd'hui
                        //Doncle formulaire doit être cloturer
                        if (resul == 1)
                        {
                            if (form.Closed == null || form.Closed.Length == 0)
                            {
                                using (context)
                                {
                                    form.Closed = "yes";

                                    context.Entry(form).State = EntityState.Modified;
                                    context.SaveChanges();
                                }
                            }
                        }
                    }
                }
            }


            return forms;
        }

        //
        // GET: /Data/Details/5

        public ActionResult Details(int id)
        {
            Form form = context.Forms.SingleOrDefault(b => b.FormId == id);

            if (form == null)
            {
                RedirectToAction("Error", "Shared", "");
            }
            return View(form);
        }

        //
        // GET: /Data/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Data/Create
        [HttpPost]
        public ActionResult Create(Form form)
        {
            if (ModelState.IsValid)
            {
                //On génère le le hash
                Random alea = new Random();

                //On génère l'url
                string url = "Response/GoToForm/";

                form.Hash = alea.Next(1000000000).ToString();
                form.Url = url + form.Hash;

                //Le formulaire n'est pas cloturé puisqu'il vient d'etre créer
                form.Closed = null;

                context.Forms.Add(form);
                context.SaveChanges();
                return RedirectToAction("ShowPath",form);
            }

            return View(form);
        }

        //
        // GET: /Data/Edit/5

        public ActionResult Edit(int id)
        {
            Form form = context.Forms.Single(p => p.FormId == id);
            if (form == null)
            {
                RedirectToAction("Error", "Shared", "");
            }
            return View(form);
        }

        //
        // POST: /Data/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, Form form)
        {
            if (ModelState.IsValid)
            {
                using (context)
                {
                    Form _form = context.Forms.Single(p => p.FormId == id);

                    _form.Title = form.Title;
                    _form.Description = form.Description;

                    context.Entry(_form).State = EntityState.Modified;
                    context.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            return View(form);
        }

        //
        // GET: /Data/Delete/5

        public ActionResult Delete(int id)
        {
            Form form = context.Forms.Single(p => p.FormId == id);
            if (form == null)
            {
                RedirectToAction("Error", "Shared", "");
            }
            return View(form);
        }

        //
        // POST: /Data/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, Form form)
        {
            //Get form to delete
            Form _form = context.Forms.Single(p => p.FormId == id);

            #region DeleteAnswers
            //Select all asnwers to this form
            List<Answer> answersToDelete = context.Answers.Where(i => i.question.form.FormId == id).ToList();

            //On supprime les réponses de la base
            foreach (Answer answerToDelete in answersToDelete)
            {
                context.Answers.Remove(answerToDelete);
            }
            #endregion

            #region DeleteQuestions

            //Select All questions to this form
            List<Question> questionsToDelete = context.Questions.Where(i => i.FormId == id).ToList();

            //On supprime chaque question
            foreach (Question questionToDelete in questionsToDelete)
            {
                context.Questions.Remove(questionToDelete);
            }

            #endregion

            #region DeleteStats

            //Select All stats to this form
            List<Stat> statsToDelete = context.Stats.Where(i => i.FormId == id).ToList();

            //On supprime chaque stat
            foreach(Stat statToDelete in statsToDelete)
            {
                context.Stats.Remove(statToDelete);
            }

            #endregion

            //Delete form
            context.Forms.Remove(_form);

            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Cloture(int id)
        {
            Form form = context.Forms.Single(p => p.FormId == id);
            if (form == null)
            {
                RedirectToAction("Error", "Shared", "");
            }
            return View(form);
        }

        [HttpPost]
        public ActionResult Cloture(int id, Form form)
        {
            if (ModelState.IsValid)
            {
                using (context)
                {
                    Form _form = context.Forms.Single(p => p.FormId == id);

                    _form.Closed = "yes";

                    context.Entry(_form).State = EntityState.Modified;
                    context.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            return View(form);
        }

        public ActionResult NotCloture(int id)
        {
            Form form = context.Forms.Single(p => p.FormId == id);
            if (form == null)
            {
                RedirectToAction("Error", "Shared", "");
            }
            return View(form);
        }

        [HttpPost]
        public ActionResult NotCloture(int id, Form form)
        {
            if (ModelState.IsValid)
            {
                using (context)
                {
                    Form _form = context.Forms.Single(p => p.FormId == id);

                    _form.Closed = null;

                    context.Entry(_form).State = EntityState.Modified;
                    context.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            return View(form);
        }

        //Renvoie vers la page pour afficher le lien pour accéder au formulaire
        public ActionResult ShowPath(Form form)
        {
            return View(form);
        }
    }
}

FormOnline/Controllers/ResponseController.cs
using FormOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormOnline.Controllers
{
    public class ResponseController : Controller
    {
        DataDbContext context = new DataDbContext();
        //
        // GET: /Response/

        public ActionResult Index()
        {
            List<Form> forms = context.Forms.Where(x => x.Closed == null).ToList();
            return View(forms);
        }

        public ActionResult GoToForm(int id)
        {
            Form form = context.Forms.SingleOrDefault(b => b.Hash == id.ToString());

            if (form == null)
            {
                return RedirectToAction("Error", "Shared");
            }

            string msgError = "";

            #region Traitement Formulaire complet
            //Si le form est cloturé
            if (form.Closed != null)
            {
                msgError = "Le formulaire est clotûré.";
            }
            else
            {
                //Si le form n'a pas de questions
                if (form.Questions == null)
                {
                    msgError = "Le formulaire n'est pas fini";
                }
                else
                {
                    //Si le form n'a pas de questions
                    if (form.Questions.Count <= 0)
                        msgError = "Le formulaire n'est pas fini";
                    else
                    {
                        //Pour chaque question, on vérifie si elle a au moins 2 réponses
                        foreach (Question quest in form.Questions)
                        {
                            if (quest.Answers == null)
                                msgError = "Le formulaire n'est pas fini";
                            else
                                if (quest.Answers.Count <= 0)
                                    msgError = "Le formulaire n'est pas fini";
                        }
                    }
                }
            }
            #endregion

            ViewData["msgError"] = msgError;

            return View(form);
        }

        //
        // GET: /Response/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Response/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Response/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Response/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Response/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Response/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Response/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

FormOnline/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormOnline.Controllers
{
    public class SharedController : Controller
    {
        public ActionResult Error()
        {
            return View();
        }
    }
}

FormOnline/Views/Shared/Copie de _Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Mon application ASP.NET MVC</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("FormOnline", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
        </div>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="Home">FormOnline</a>
            </div>
            <div class="navbar-collapse collapse" style="height: 1px;">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Formulaires", "Index", "Data")</li>
                    <li>@Html.ActionLink("Questions", "Index", "Question")</li>
                    <li>@Html.ActionLink("Réponses", "Index", "Answer")</li>
                    <li>@Html.ActionLink("Répondre", "Index", "Response")</li>
                    <li>@Html.ActionLink("Statistiques", "Index", "Stat")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - FormOnline</p>
            </div>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

FormOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Mon application ASP.NET MVC</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    @*<header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("FormOnline", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
        </div>
    </header>*@
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                        <div class="container">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="Home">FormOnline</a>
                            </div>
                            <div class="navbar-collapse collapse" style="height: 1px;">
                                <ul class="nav navbar-nav">
                                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                                    <li>@Html.ActionLink("Formulaires", "Index", "Data")</li>
                                    <li>@Html.ActionLink("Questions", "Index", "Question")</li>
                                    <li>@Html.ActionLink("Réponses", "Index", "Answer")</li>
                                    <li>@Html.ActionLink("Répondre", "Index", "Response")</li>
                                    <li>@Html.ActionLink("Statistiques", "Index", "Stat")</li>
                                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                </ul>
                            </div>
                            <!--/.nav-collapse -->
                        </div>
                    </div>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - FormOnline</p>
            </div>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>